VOMHack/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('adminpanel.urls')),
    url(r'^', include('login.urls')),
]

adminpanel/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'adminpanel'

urlpatterns = [
    url(r'^home/', views.Home.as_view(), name='home'),
    url(r'^pending/', views.Pending.as_view(), name='pending'),
    url(r'^resolved', views.Resolved.as_view(), name='resolved'),
]

login/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views


app_name = 'login'
urlpatterns = [
    url(r'^$', views.login.as_view(), name='login'),
    url(r'^logout',views.logout,name='logout'),
    url(r'^', include('adminpanel.urls', namespace='adminpanel')),

]

login/models.py
from django.db import models

# Create your models here.

adminpanel/views.py
from django.shortcuts import render, redirect
import pyrebase
from django.views import View

config = {
    'apiKey': "AIzaSyC-Ile_oqnvyZKO4aEHNp7J7BNu8lDvVoM",
    'authDomain': "voiceofmumbai-8ca1f.firebaseapp.com",
    'databaseURL': "https://voiceofmumbai-8ca1f.firebaseio.com",
    'projectId': "voiceofmumbai-8ca1f",
    'storageBucket': "voiceofmumbai-8ca1f.appspot.com",
    'messagingSenderId': "724490822942"
}

firebase = pyrebase.initialize_app(config)
db = firebase.database()

class Home(View):
    template_name = 'adminpanel/home.html'

    def get(self,request):

        grievances = db.child('grievances').get().val()
        tc = 0
        pending = 0
        resolved = 0
        flagged = 0
        for keys in grievances:
            tc += 1
            if grievances[keys]['spam'] > 0:
                flagged += 1
            if grievances[keys]['status'] == 'pending':
                pending += 1
            elif grievances[keys]['status'] == 'resolved':
                resolved += 1

        data = {'tc':tc, 'pend': pending, 'res': resolved, 'flag':flagged}

        return render(request, self.template_name, data)

class Pending(View):
    template_name = 'adminpanel/pending.html'

    def get(self, request):

        data = db.child('grievances').get().val()
        sendata = []
        for keys in data:
            if data[keys]['status'] == 'pending':
                sendata.append((data[keys]['pic_url'],data[keys]['description'],data[keys]['location'],data[keys]['user_name'],keys))

        return render(request, self.template_name, {'data':sendata})

    def post(self, request):

        db.child('grievances').child(request.POST['hid_input']).update({'status': request.POST['status']})
        return redirect('adminpanel:pending')


class Resolved(View):
    template_name = 'adminpanel/resolved.html'

    def get(self, request):

        data = db.child('grievances').get().val()
        sendata = []
        for keys in data:
            if data[keys]['status'] == 'resolved':
                sendata.append((data[keys]['pic_url'],data[keys]['description'],data[keys]['location'],data[keys]['user_name'],keys))

        return render(request, self.template_name, {'data':sendata})

    def post(self, request):

        db.child('grievances').child(request.POST['hid_input']).update({'status': request.POST['status']})
        return redirect('adminpanel:resolved')

login/views.py
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
import pyrebase
from django import forms
from django.views import View

config = {
    'apiKey': "AIzaSyC-Ile_oqnvyZKO4aEHNp7J7BNu8lDvVoM",
    'authDomain': "voiceofmumbai-8ca1f.firebaseapp.com",
    'databaseURL': "https://voiceofmumbai-8ca1f.firebaseio.com",
    'projectId': "voiceofmumbai-8ca1f",
    'storageBucket': "voiceofmumbai-8ca1f.appspot.com",
    'messagingSenderId': "724490822942"
}

firebase = pyrebase.initialize_app(config)
db = firebase.database()

# Create your views here.

class login(View):
    template_name = 'login/login.html'

    # display blank form
    def get(self, request):
        return render(request, self.template_name)

    # add to database
    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        admin = db.child('Admin').get().val()
        aduser = admin['email']
        adpass = admin['password']
        if username == aduser and password == str(adpass):
            return HttpResponseRedirect('/home')
        else:
            raise forms.ValidationError('Looks like a username with that email or password already exists')

def logout(request):
    auth.logout(request)
    return redirect('login:login')

adminpanel/templates/adminpanel/home.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Admin Panel</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    {% load staticfiles %}
    <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'adminpanel/css/materialdesignicons.min.css' %}">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'adminpanel/css/style.css' %}"">
  <!-- endinject -->
</head>

<body>
  <div class="body-wrapper">
    <!-- partial:partials/_sidebar.html -->
    <aside class="mdc-persistent-drawer mdc-persistent-drawer--open">
      <nav class="mdc-persistent-drawer__drawer">
        <div class="mdc-persistent-drawer__toolbar-spacer">
          <a href="{% url 'adminpanel:home' %}" class="brand-logo" style="padding-left: 25px; font-family: 'K2D', sans-serif; font-size: 24px;">
            More Options
          </a>
        </div>
        <div class="mdc-list-group">
          <nav class="mdc-list mdc-drawer-menu">
            <div class="mdc-list-item mdc-drawer-item">
              <a class="mdc-drawer-link" href="{% url 'adminpanel:home' %}">
                <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon" aria-hidden="true">desktop_mac</i>
                Dashboard
              </a>
            </div>
            <div class="mdc-list-item mdc-drawer-item" href="#" data-toggle="expansionPanel" target-panel="ui-sub-menu">
              <a class="mdc-drawer-link" href="#">
                <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon" aria-hidden="true">dashboard</i>
                Grievances
                <i class="mdc-drawer-arrow material-icons">arrow_drop_down</i>
              </a>
              <div class="mdc-expansion-panel" id="ui-sub-menu">
                <nav class="mdc-list mdc-drawer-submenu">
                  <div class="mdc-list-item mdc-drawer-item">
                    <a class="mdc-drawer-link" href="{% url 'adminpanel:pending' %}">
                      Pending
                    </a>
                  </div>
                  <div class="mdc-list-item mdc-drawer-item">
                    <a class="mdc-drawer-link" href="{% url 'adminpanel:resolved' %}">
                      Solved
                    </a>
                  </div>
                </nav>
              </div>
            </div>
          </nav>
        </div>
      </nav>
    </aside>
    <!-- partial -->
    <!-- partial:partials/_navbar.html -->
    <header class="mdc-toolbar mdc-elevation--z4 mdc-toolbar--fixed">
      <div class="mdc-toolbar__row">
        <section class="mdc-toolbar__section mdc-toolbar__section--align-start">
          <a href="#" class="menu-toggler material-icons mdc-toolbar__menu-icon">menu</a>
        </section>
        <section class="mdc-toolbar__section mdc-toolbar__section--align-end" role="toolbar">
        	
          	<div class="mdc-menu-anchor" style="color: white; padding-right: 10px;">
       			Admin
          	</div>
          
          <div class="mdc-menu-anchor mr-1">
            <a href="#" class="mdc-toolbar__icon toggle mdc-ripple-surface" data-toggle="dropdown" toggle-dropdown="logout-menu" data-mdc-auto-init="MDCRipple">
              <i class="material-icons">more_vert</i>
            </a>
            <div class="mdc-simple-menu mdc-simple-menu--right" tabindex="-1" id="logout-menu">
                <ul class="mdc-simple-menu__items mdc-list" role="menu" aria-hidden="true">
                  <li class="mdc-list-item" role="menuitem" tabindex="0">
                    <i class="material-icons mdc-theme--primary mr-1">power_settings_new</i>
                    <a href='/logout'>Logout</a>
                  </li>
                </ul>
            </div>
          </div>
        </section>
      </div>
    </header>
    <!-- partial -->
    <div class="page-wrapper mdc-toolbar-fixed-adjust">
      <main class="content-wrapper">
        <div class="mdc-layout-grid">
          <div class="mdc-layout-grid__inner">
            <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-8">
              <div class="mdc-layout-grid__inner">
                <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6">
                  <div class="mdc-card py-3 pl-2 d-flex flex-row align-item-center">
                    <div class="mdc--tile mdc--tile-danger rounded">
                      <i class="mdi mdi-clock text-white icon-md"></i>
                    </div>
                    <div class="text-wrapper pl-1">
                      <h3 class="mdc-typography--display1 font-weight-bold mb-1">{{ pend }}</h3>
                      <p class="font-weight-normal mb-0 mt-0">Pending Issues</p>
                    </div>
                  </div>
                </div>
                <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6">
                  <div class="mdc-card py-3 pl-2 d-flex flex-row align-item-center">
                    <div class="mdc--tile mdc--tile-success rounded">
                      <i class="mdi mdi-check-circle text-white icon-md"></i>
                    </div>
                    <div class="text-wrapper pl-1">
                      <h3 class="mdc-typography--display1 font-weight-bold mb-1">{{ res }}</h3>
                      <p class="font-weight-normal mb-0 mt-0">Resolved Issues</p>
                    </div>
                  </div>
                </div>
                <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6">
                  <div class="mdc-card py-3 pl-2 d-flex flex-row align-item-center">
                    <div class="mdc--tile mdc--tile-warning rounded">
                      <i class="mdi mdi-close-octagon text-white icon-md"></i>
                    </div>
                    <div class="text-wrapper pl-1">
                      <h3 class="mdc-typography--display1 font-weight-bold mb-1">{{ flag }}</h3>
                      <p class="font-weight-normal mb-0 mt-0">Flagged Issues</p>
                    </div>
                  </div>
                </div>
                <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6">
                  <div class="mdc-card py-3 pl-2 d-flex flex-row align-item-center">
                    <div class="mdc--tile mdc--tile-primary rounded">
                      <i class="mdi mdi-database text-white icon-md"></i>
                    </div>
                    <div class="text-wrapper pl-1">
                      <h3 class="mdc-typography--display1 font-weight-bold mb-1">{{ tc }}</h3>
                      <p class="font-weight-normal mb-0 mt-0">Total Issues</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>
        </div>
      </main>
      <!-- partial:partials/_footer.html -->
      <footer>
        <div class="mdc-layout-grid">
          <div class="mdc-layout-grid__inner">
            <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6">
              <span class="text-muted">Copyright © 2018 <a class="text-green" href="{% url 'adminpanel:home' %}" target="_blank">Voices Of Mumbai</a>. All rights reserved.</span>
            </div>
            <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6 d-flex justify-content-end">
              <span class="mt-0 text-right">KJSCE Hackathon</span>
            </div>
          </div>
        </div>
      </footer>
      <!-- partial -->
    </div>
  </div>
  <!-- body wrapper -->
  <!-- plugins:js -->
  <script src="{% static 'adminpanel/js/material-components-web.min.js' %}"></script>
  <script src="{% static 'adminpanel/js/jquery.min.js' %}"></script>
  <!-- endinject -->
  <!-- inject:js -->
  <script src="{% static 'adminpanel/js/misc.js' %}"></script>
  <script src="{% static 'adminpanel/js/material.js' %}"></script>
  <!-- endinject -->
  <!-- Custom js for this page-->
  <script src="{% static 'adminpanel/js/dashboard.js' %}"></script>
  <!-- End custom js for this page-->
</body>

</html>

adminpanel/templates/adminpanel/pending.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Admin Panel</title>
    {% load staticfiles %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'adminpanel/css/materialdesignicons.css' %}">
  <link rel="stylesheet" href="{% static 'adminpanel/css/style.css' %}">
    <style type="text/css">
        .bordering{
            border:2px solid black;
            width: 275px;
            height: auto;
            padding-left: 2px;
            margin-left:15px;
            margin-top:15px;
        }
    </style>
</head>

<body>
  <div class="body-wrapper">
    <!-- partial:partials/_sidebar.html -->
    <aside class="mdc-persistent-drawer mdc-persistent-drawer--open">
      <nav class="mdc-persistent-drawer__drawer">
        <div class="mdc-persistent-drawer__toolbar-spacer">
          <a href="{% url 'adminpanel:home' %}" class="brand-logo" style="padding-left: 25px; font-family: 'K2D', sans-serif; font-size: 24px;">
            More Options
          </a>
        </div>
        <div class="mdc-list-group">
          <nav class="mdc-list mdc-drawer-menu">
            <div class="mdc-list-item mdc-drawer-item">
              <a class="mdc-drawer-link" href="{% url 'adminpanel:home' %}">
                <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon" aria-hidden="true">desktop_mac</i>
                Dashboard
              </a>
            </div>
             <div class="mdc-list-item mdc-drawer-item" href="#" data-toggle="expansionPanel" target-panel="ui-sub-menu">
              <a class="mdc-drawer-link" href="#">
                <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon" aria-hidden="true">dashboard</i>
                Grievances
                <i class="mdc-drawer-arrow material-icons">arrow_drop_down</i>
              </a>
              <div class="mdc-expansion-panel" id="ui-sub-menu">
                <nav class="mdc-list mdc-drawer-submenu">
                  <div class="mdc-list-item mdc-drawer-item">
                    <a class="mdc-drawer-link" href="{% url 'adminpanel:pending' %}">
                      Pending
                    </a>
                  </div>
                  <div class="mdc-list-item mdc-drawer-item">
                    <a class="mdc-drawer-link" href="{% url 'adminpanel:resolved' %}">
                      Solved
                    </a>
                  </div>
                </nav>
              </div>
            </div>
          </nav>
        </div>
      </nav>
    </aside>
    <header class="mdc-toolbar mdc-elevation--z4 mdc-toolbar--fixed">
      <div class="mdc-toolbar__row">
        <section class="mdc-toolbar__section mdc-toolbar__section--align-start">
          <a href="#" class="menu-toggler material-icons mdc-toolbar__menu-icon">menu</a>
        </section>
        <section class="mdc-toolbar__section mdc-toolbar__section--align-end" role="toolbar">

            <div class="mdc-menu-anchor" style="color: white; padding-right: 10px;">
            Admin
            </div>

          <div class="mdc-menu-anchor mr-1">
            <a href="#" class="mdc-toolbar__icon toggle mdc-ripple-surface" data-toggle="dropdown" toggle-dropdown="logout-menu" data-mdc-auto-init="MDCRipple">
              <i class="material-icons">more_vert</i>
            </a>
            <div class="mdc-simple-menu mdc-simple-menu--right" tabindex="-1" id="logout-menu">
                <ul class="mdc-simple-menu__items mdc-list" role="menu" aria-hidden="true">
                  <li class="mdc-list-item" role="menuitem" tabindex="0">
                    <i class="material-icons mdc-theme--primary mr-1">power_settings_new</i>
                    <a href='logout'>Logout</a>
                  </li>
                </ul>
            </div>
          </div>
        </section>
      </div>
    </header>
    <!-- partial -->
    <div class="page-wrapper mdc-toolbar-fixed-adjust">
      <main class="content-wrapper" style="overflow-y: scroll;">
        <div class="mdc-layout-grid">
      <!-- partial:partials/_footer.html -->
            {% for pu, d, loc, uuid, key in data %}
                <div style="display: inline;">
                    <div class="container" style="width: auto;  border: 2px solid black; float: left; margin-right: 10px; text-align: justify;">
             <div class="card " style="width:275px;height:150px;padding-left: 10px;">
                 <div class="card-body">
                     <h4 class="card-title"><u>{{ uuid }}</u></h4><p style="color:gray">{{ loc }}</p>

                    <p class="card-text" style="line-height:1.5ems">{{ d }}</p>
                <form action="{% url 'adminpanel:pending' %}" method="post" id="form1">
                    {% csrf_token %}
                    <select name="status" form="form1">
                        <option value="pending">Pending</option>
                        <option value="resolved">Resolved</option>
                    </select>&nbsp;&nbsp;&nbsp;
                    <input type="hidden" name="hid_input" value="{{ key }}"></input>

                    <input type="submit" value="Done" class="btn btn-primary"></input>
                </form>
             </div>
         </div>
            <br>
                </div>
                </div>
            {% endfor %}
        </div>
      </main>
      <footer>
        <div class="mdc-layout-grid">
          <div class="mdc-layout-grid__inner">
            <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6">
              <span class="text-muted">Copyright © 2018 <a class="text-green" href="/home" target="_blank">Voices Of Mumbai</a>. All rights reserved.</span>
            </div>
            <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6 d-flex justify-content-end">
              <span class="mt-0 text-right">KJSCE Hackathon</span>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </div>
 <script src="{% static 'adminpanel/js/material-components-web.min.js' %}"></script>
  <script src="{% static 'adminpanel/js/jquery.min.js' %}"></script>
  <script src="{% static 'adminpanel/js/misc.js' %}"></script>
  <script src="{% static 'adminpanel/js/material.js' %}"></script>
  <script src="{% static 'adminpanel/js/dashboard.js' %}"></script>
</body>

</html>

adminpanel/templates/adminpanel/resolved.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Admin Panel</title>
    {% load staticfiles %}

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'adminpanel/css/materialdesignicons.css' %}">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'adminpanel/css/style.css' %}">

  <!-- endinject -->
</head>

<body>
  <div class="body-wrapper">
    <!-- partial:partials/_sidebar.html -->
    <aside class="mdc-persistent-drawer mdc-persistent-drawer--open">
      <nav class="mdc-persistent-drawer__drawer">
        <div class="mdc-persistent-drawer__toolbar-spacer">
          <a href="{% url 'adminpanel:home' %}" class="brand-logo" style="padding-left: 25px; font-family: 'K2D', sans-serif; font-size: 24px;">
            More Options
          </a>
        </div>
        <div class="mdc-list-group">
          <nav class="mdc-list mdc-drawer-menu">
            <div class="mdc-list-item mdc-drawer-item">
              <a class="mdc-drawer-link" href="{% url 'adminpanel:home' %}">
                <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon" aria-hidden="true">desktop_mac</i>
                Dashboard
              </a>
            </div>
             <div class="mdc-list-item mdc-drawer-item" href="#" data-toggle="expansionPanel" target-panel="ui-sub-menu">
              <a class="mdc-drawer-link" href="#">
                <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon" aria-hidden="true">dashboard</i>
                Grievances
                <i class="mdc-drawer-arrow material-icons">arrow_drop_down</i>
              </a>
              <div class="mdc-expansion-panel" id="ui-sub-menu">
                <nav class="mdc-list mdc-drawer-submenu">
                  <div class="mdc-list-item mdc-drawer-item">
                    <a class="mdc-drawer-link" href="{% url 'adminpanel:pending' %}">
                      Pending
                    </a>
                  </div>
                  <div class="mdc-list-item mdc-drawer-item">
                    <a class="mdc-drawer-link" href="{% url 'adminpanel:resolved' %}">
                      Solved
                    </a>
                  </div>
                </nav>
              </div>
            </div>
          </nav>
        </div>
      </nav>
    </aside>
    <!-- partial -->
    <!-- partial:partials/_navbar.html -->
    <header class="mdc-toolbar mdc-elevation--z4 mdc-toolbar--fixed">
      <div class="mdc-toolbar__row">
        <section class="mdc-toolbar__section mdc-toolbar__section--align-start">
          <a href="#" class="menu-toggler material-icons mdc-toolbar__menu-icon">menu</a>
        </section>
        <section class="mdc-toolbar__section mdc-toolbar__section--align-end" role="toolbar">
          
            <div class="mdc-menu-anchor" style="color: white; padding-right: 10px;">
            Admin
            </div>
          
          <div class="mdc-menu-anchor mr-1">
            <a href="#" class="mdc-toolbar__icon toggle mdc-ripple-surface" data-toggle="dropdown" toggle-dropdown="logout-menu" data-mdc-auto-init="MDCRipple">
              <i class="material-icons">more_vert</i>
            </a>
            <div class="mdc-simple-menu mdc-simple-menu--right" tabindex="-1" id="logout-menu">
                <ul class="mdc-simple-menu__items mdc-list" role="menu" aria-hidden="true">
                  <li class="mdc-list-item" role="menuitem" tabindex="0">
                    <i class="material-icons mdc-theme--primary mr-1">power_settings_new</i>
                    <a href='/logout'>Logout</a>
                  </li>
                </ul>
            </div>
          </div>
        </section>
      </div>
    </header>
    <!-- partial -->
    <div class="page-wrapper mdc-toolbar-fixed-adjust">
      <main class="content-wrapper" style="overflow-y: scroll;">
        <div class="mdc-layout-grid">
      <!-- partial:partials/_footer.html -->
            {% for pu, d, loc, uuid, key in data %}
                <div style="display: inline;">
                    <div class="container" style="width: auto;  border: 2px solid black; float: left; margin-right: 10px; text-align: justify; padding-top: 10px;">
                         <div class="card" style="width:275px;height:150px;padding-left: 10px; padding-top: 10px; padding-right: 10px; ">
                             <div class="card-body" style="padding-right: 10px; ">
                                <h4 class="card-title">{{ uuid }}</h4><br><span style="color:gray">{{ loc }}</span>

                                <p class="card-text" style="line-height:1.5em;">{{ d }}</p>
                                <form action="{% url 'adminpanel:resolved' %}" method="post" id="form1">
                                    {% csrf_token %}
                                    <select name="status" form="form1">
                                        <option value="pending">Pending</option>
                                        <option value="resolved">Resolved</option>
                                    </select>&nbsp;&nbsp;&nbsp;
                                     <input type="hidden" name="hid_input" value="{{ key }}">

                                     <input type="submit" class="btn btn-primary">Done</input>
                                </form>
                            </div>
                         </div>
                        <br>
                    </div>
                </div>
            {% endfor %}
        </div>
      </main>
      <footer>
        <div class="mdc-layout-grid">
          <div class="mdc-layout-grid__inner">
            <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6">
              <span class="text-muted">Copyright © 2018 <a class="text-green" href="/home" target="_blank">Voices Of Mumbai</a>. All rights reserved.</span>
            </div>
            <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6 d-flex justify-content-end">
              <span class="mt-0 text-right">KJSCE Hackathon</span>
            </div>
          </div>
        </div>
      </footer>
      <!-- partial -->
    </div>
  </div>
   <script src="{% static 'adminpanel/js/material-components-web.min.js' %}"></script>
  <script src="{% static 'adminpanel/js/jquery.min.js' %}"></script>
  <!-- endinject -->
  <!-- inject:js -->
  <script src="{% static 'adminpanel/js/misc.js' %}"></script>
  <script src="{% static 'adminpanel/js/material.js' %}"></script>
  <!-- endinject -->
  <!-- Custom js for this page-->
  <script src="{% static 'adminpanel/js/dashboard.js' %}"></script>
</body>

</html>

login/templates/login/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Login</title>
    {% load staticfiles %}
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'login/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="site-name">
					Voices Of Mumbai
				</div>
				<div class="login100-pic js-tilt" data-tilt>
					<img src="{% static 'login/images/img-01.png' %}" alt="IMG">
				</div>

				<form class="login100-form validate-form" method="POST">
					{% csrf_token %}
					<span class="login100-form-title">
					    Admin Login
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<input class="input100" type="text" name="username" placeholder="Username">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-user" aria-hidden="true"></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn" type="submit">
							Login
						</button>
					</div>

				</form>
			</div>
		</div>
	</div>
</body>
</html>

login/templates/login/logout.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    You have successfully logged out.
    <a href="/">Home</a>
</body>
</html>